openapi: 3.0.0
info:
  title: frost.tools.spec
  version: '1.0'
  contact:
    name: Sabrina Frost
    url: 'https://sabrinafrost.com'
    email: api@sabrinafrost.com
  description: ''
  x-logo:
      url: "./common/images/logo.png"
servers:
  - url: 'https://frost.tools'
    description: Production
  - url: 'http://localhost:8000'
    description: Development
x-tagGroups:
  - name: Tesla
    tags:
      - Authentication
      - Commands
  - name: Utilities
    tags:
      - Encryption
      - Other
paths:
  /tesla/auth:
    delete:
      summary: Revoke access token
      tags: ["Authentication"]
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: patch-tesla
      description: Revoke access token
      parameters:
        - schema:
            type: string
            maxLength: 0
          in: header
          name: data
          description: Encrypted Tesla data
          required: true
        - schema:
            type: string
          in: header
          name: encryption_key
          description: Encryption key (for encrypting / decrypting Tesla authentication data)
          required: true
    post:
      summary: Get access token and vehicle data
      tags: ["Authentication"]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  type: object
              examples:
                example-1:
                  value:
                    'Tesla #1': snatoheusntahoeusntoeghu
        '204':
          description: No Content
        '401':
          description: Unauthorized
      operationId: post-tesla
      description: Get new access token and vehicle data
      parameters:
        - schema:
            type: string
            maxLength: 0
          in: header
          name: tesla_email
          description: Tesla account email address
          required: true
        - schema:
            type: string
          in: header
          name: tesla_password
          description: Tesla account password
          required: true
        - schema:
            type: string
          in: header
          name: encryption_key
          description: Encryption key (for encrypting / decrypting Tesla authentication data)
          required: true
    put:
      summary: Refresh access token
      tags: ["Authentication"]
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: put-tesla
      description: Refresh access token
      parameters:
        - schema:
            type: string
            maxLength: 0
          in: header
          name: data
          description: Encrypted Tesla data
          required: true
        - schema:
            type: string
          in: header
          name: encryption_key
          description: Encryption key (for encrypting / decrypting Tesla authentication data)
          required: true
  /utilities/week:
    get:
      summary: Get week number
      tags: ["Other"]
      responses:
        '200':
          description: OK
          headers: {}
      operationId: get-utilities
    parameters: []
  /utilities/encrypt:
    post:
      summary: Encrypt data
      tags: ["Encryption"]
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: post-utilities-encrypt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                key:
                  type: string
                  format: password
              required:
                - data
                - key
        description: ''
  /utilities/decrypt:
    post:
      summary: Decrypt data
      tags: ["Encryption"]
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: post-utilities-encrypt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                key:
                  type: string
                  format: password
              required:
                - data
                - key
        description: ''
components:
  schemas: {}
  securitySchemes: {}
