openapi: 3.0.0
info:
  title: frost.tools.utilities.spec
  version: '1.0'
  contact:
    name: Sabrina Frost
    url: 'https://sabrinafrost.com'
    email: api@sabrinafrost.com
  description: 'A frost.tools partial spec'
  
paths:
  week:
    get:
      summary: Get week number
      tags:
        - Other
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  week:
                    type: number
                    description: ISO 8601 week number
              examples:
                example-1:
                  value:
                    42
      operationId: week
      description: This returns the ISO 8601 week of the year.
    parameters: []
  encrypt:
    post:
      summary: Encrypt data
      tags:
        - Encryption
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  encrypted:
                    type: string
                    description: The encrypted text
              examples:
                example-1:
                  value:
                    encrypted: U2FsdGVkX1+h4AibsBq7Xeer/L8GT4M8e8egWPpIfjlSVKbRkPIV4fvv+G+wbT5eeEkqfjTNyQpX8cl+m28NXzygFSgTrBNEOIdiek7pJnR+MsWOkdksWGOpylI30VDD6KCjGQTmwS7MRwJkT8n1R2DT1qisiiDFkYLZxT93Zcw=
        '400':
          $ref: '#/responses/400'
      operationId: encrypt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  description: The text you would like to encrypt
                key:
                  type: string
                  format: password
                  description: 'A key (or password, if you will) that is used to encrypt and decrypt this data'
        description: ''
      description: This will encrypt text.
  decrypt:
    post:
      summary: Decrypt data
      tags:
        - Encryption
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  decrypted:
                    type: string
                    description: The decrypted text
              examples:
                example-1:
                  value:
                    decrypted: "Wow! This text was encrypted and now it's not!"
        '400':
          $ref: '#/responses/400'
        '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: '#/responses/error'
                examples:
                  example-1:
                    value:
                      message: The encryption key provided cannot be used to decrypt this data
                      error: Unauthorized
                      statusCode: 401       
      operationId: decrypt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  description: The text you would like to decrypt
                key:
                  type: string
                  format: password
                  description: 'A key (or password, if you will) that is used to encrypt and decrypt this data'
        description: ''
      description: This will decrypt encrypted text (as long as it was encrypted using this API).

common:
  $ref: 'common.yaml'

responses:
  error:
    $ref: '#/common/components/schemas/error'
  '400':
    $ref: '#/common/components/schemas/400'

  